this.phaseList = [
    { phaseName: '策划生成', phaseStatus: 'not_do' },
    {
        bdbMatters: {
            completedNum: 0,
            list: [],
            notProcessedNum: 0,
            processingNum: 0,
        },
        completedNum: 0,
        notProcessedNum: 0,
        phaseName: '要素融通',
        processingNum: 0,
    },
    {
        bdbMatters: {
            completedNum: 0,
            list: [],
            notProcessedNum: 0,
            processingNum: 0,
        },
        mainMatters: {
            list: [
                {
                    actionStatus: '正式出文[按期][合格]',
                    commitmentTimeLimit: '1',
                    mattersId: '3713000102202',
                    mattersName: '建设用地规划许可证',
                    state: 1,
                    status: '按期办结',
                    unitName: '临沂市行政审批服务局',
                },
                {
                    actionStatus: '正式出文[按期][合格]',
                    commitmentTimeLimit: '1',
                    mattersId: '3713000102202',
                    mattersName: '建设用地规划许可证',
                    state: 1,
                    status: '按期办结',
                    unitName: '临沂市行政审批服务局',
                },
                {
                    actionStatus: '正式出文[按期][合格]',
                    commitmentTimeLimit: '1',
                    mattersId: '3713000102202',
                    mattersName: '建设用地规划许可证',
                    state: 1,
                    status: '按期办结',
                    unitName: '临沂市行政审批服务局',
                },
                {
                    actionStatus: '正式出文[按期][合格]',
                    commitmentTimeLimit: '1',
                    mattersId: '3713000102202',
                    mattersName: '建设用地规划许可证',
                    state: 1,
                    status: '按期办结',
                    unitName: '临沂市行政审批服务局',
                },
            ],
            completedNum: 1,
            notProcessedNum: 3,
            processingNum: 0,
        },
        parallelMatters: {
            list: [
                {
                    commitmentTimeLimit: '5',
                    mattersId: '370130005002',
                    mattersName: '金属冶炼建设项目安全设施设计审查',
                    state: 0,
                    status: '未申报',
                    unitName: '兰山区应急管理局',
                },
            ],
            completedNum: 0,
            notProcessedNum: 6,
            processingNum: 0,
        },

        completedNum: 1,
        notProcessedNum: 3,
        phaseName: '立项用地规划许可阶段',
        phaseStatus: 'done',
        processingNum: 0,
    },
];
